export const FETCH_GSEARCH = 'FETCH_GSEARCH';

export const BUTTON_GENERATE = 'BUTTON_GENERATE';
export const BUTTON_DELETE = 'BUTTON_DELETE';
export const BUTTON_CLICK = 'BUTTON_CLICK';

export const SEGMENT_GENERATE = 'SEGMENT_GENERATE';
export const SEGMENT_DELETE = 'SEGEMENT_DELETE';
export const SEGMENT_SAVE = 'SEGMENT_SAVE';